name: Run PHPUnit tests

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    tests:
        steps:
          - name: Test Laravel 6.x
            uses: ../actions/test.matrix.yml
            with:
                php: [7.2, 7.3]
                laravel: [6.*]
                dependency: [prefer-stable]

          - name: Test Laravel 7.x
            uses: ../actions/test.matrix.yml
            with:
                php: [7.2.5, 7.3, 7.4]
                laravel: [7.*]
                dependency: [prefer-lowest, prefer-stable]